import { IManagerAccount } from "../../Manager/ManagerTypes";
import { ICurrency, IStatus } from "../Common";
import { IPropertyInsights } from "../Insights/InsightsTypes";
import {
  IPropertyLocation,
  IPropertyLocationCreation,
} from "../Location/LocationTypes";
import {
  IPropertyImageOrVideo,
  IPropertyImageOrVideoCreationOrUpdate,
} from "../Media/ImageOrVideoTypes";

export type IResidentialRentalPropertyCreation = {
  managerId: number;
  numberOfRooms: number;
  rentAmount: number;
  sizeNumber: number;
  numberOfGarages: number;
  hasElectricity: boolean;
  hasSwimmingPool: boolean;
  hasWater: boolean;
  hasBoreHole: boolean;
  isPlustered: boolean;
  isPainted: boolean;
  isPaved: boolean;
  isTiled: boolean;
  hasCeiling: boolean;
  typeOfExteriorSecurity: string;
  numberOfRoomsToLet: number;
  currency: ICurrency;
  isFullHouse: boolean;
  bathrooms: number;
  bedrooms: number;
  status: string;
  yearBuilt: number;
  storeys: number;
  type: string;
  sizeDimensions: string;
  otherInteriorFeatures: string[];
  otherExteriorFeatures: string[];
  tenantRequirements: string[];
  marketingStatement: string;
  propertyLocation: IPropertyLocationCreation;
  media: IPropertyImageOrVideoCreationOrUpdate[];
};

export type IResidentialRentalProperty = {
  id: number;
  managerId: number;
  uniqueId: number;
  numberOfRooms: number;
  rentAmount: number;
  sizeNumber: number;
  numberOfGarages: number;
  hasElectricity: boolean;
  hasSwimmingPool: boolean;
  hasWater: boolean;
  hasBoreHole: boolean;
  isFavorite: boolean;
  isPaved: boolean;
  isTiled: boolean;
  hasCeiling: boolean;
  typeOfExteriorSecurity: string;
  numberOfRoomsToLet: number;
  currency: ICurrency;
  isFullHouse: boolean;
  bathrooms: number;
  isPlustered: boolean;
  bedrooms: number;
  status: string;
  isPainted: boolean;
  yearBuilt: number;
  storeys: number;
  type: string;
  sizeDimensions: string;
  otherInteriorFeatures: string[];
  otherExteriorFeatures: string[];
  tenantRequirements: string[];
  marketingStatement: string;
  postedTime: string;
  insights: IPropertyInsights;
  propertyLocation: IPropertyLocation;
  media: IPropertyImageOrVideo[];
};

export type IResidentialRentalPropertyWithManager = {
  id: number;
  managerId: number;
  uniqueId: number;
  numberOfRooms: number;
  rentAmount: number;
  sizeNumber: number;
  numberOfGarages: number;
  hasElectricity: boolean;
  hasSwimmingPool: boolean;
  hasWater: boolean;
  hasBoreHole: boolean;
  isFavorite: boolean;
  isPlustered: boolean;
  isPaved: boolean;
  isTiled: boolean;
  hasCeiling: boolean;
  typeOfExteriorSecurity: string;
  numberOfRoomsToLet: number;
  currency: ICurrency;
  isFullHouse: boolean;
  bathrooms: number;
  bedrooms: number;
  status: string;
  yearBuilt: number;
  storeys: number;
  isPainted: boolean;
  type: string;
  sizeDimensions: string;
  otherInteriorFeatures: string[];
  otherExteriorFeatures: string[];
  tenantRequirements: string[];
  marketingStatement: string;
  postedTime: string;
  insights: IPropertyInsights;
  propertyLocation: IPropertyLocation;
  media: IPropertyImageOrVideo[];
  manager: IManagerAccount;
};

export type IResidentialRentalPropertyUpdate = {
  id: number;
  managerId: number;
  uniqueId: number;
  numberOfRooms: number;
  rentAmount: number;
  sizeNumber: number;
  numberOfGarages: number;
  bathrooms: number;
  bedrooms: number;
  numberOfRoomsToLet: number;
  yearBuilt: number;
  storeys: number;
  hasElectricity: boolean;
  hasSwimmingPool: boolean;
  hasWater: boolean;
  hasBoreHole: boolean;
  isPaved: boolean;
  isPlustered: boolean;
  isTiled: boolean;
  hasCeiling: boolean;
  isFullHouse: boolean;
  isPainted: boolean;
  currency: ICurrency;
  status: IStatus;
  typeOfExteriorSecurity: string;
  type: string;
  sizeDimensions: string;
  marketingStatement: string;
  otherInteriorFeatures: string[];
  otherExteriorFeatures: string[];
  tenantRequirements: string[];
  newMedia: IPropertyImageOrVideoCreationOrUpdate[];
  mediaToDelete: IPropertyImageOrVideo[];
  mediaToUpdate: IPropertyImageOrVideo[];
};
