export type ContentType = 
  "none"|
  "addressCity"|
  "addressCityAndState"|
  "addressState"|
  "birthdate"|
  "birthdateDay"|
  "birthdateMonth"|
  "birthdateYear"|
  "countryName"|
  "creditCardExpiration"|
  "creditCardExpirationMonth"|
  "creditCardExpirationYear"|
  "creditCardFamilyName"|
  "creditCardGivenName"|
  "creditCardMiddleName"|
  "creditCardName"|
  "creditCardNumber"|
  "creditCardSecurityCode"|
  "creditCardType"|
  "emailAddress"|
  "familyName"|
  "fullStreetAddress"|
  "givenName"|
  "jobTitle"|
  "location"|
  "middleName"|
  "name"|
  "namePrefix"|
  "nameSuffix"|
  "newPassword"|
  "nickname"|
  "oneTimeCode"|
  "organizationName"|
  "password"|
  "postalCode"|
  "streetAddressLine1"|
  "streetAddressLine2"|
  "sublocality"|
  "telephoneNumber"|
  "URL"|
  "username"
